### PR TITLE
Add dark theme

### PR DESCRIPTION
**Pull request by pizzafox**
This adds a basic dark theme to the global SCSS by using the `prefers-color-scheme` media query.
Some of the colors are arbitrary. You might want to tweak them to your liking, especially the navbar background color (finding something with good contrast is hard!).

PS: If you add the `hacktoberfest` topic to this repository pull requests like [this count towards me getting a t-shirt & stickers](https://hacktoberfest.digitalocean.com/)

### CODE REVIEW

**Comment by tekknolagi** [comment]
Hey, pretty neat. Do you have any screenshots? I'm away from a computer right now.

**Comment by pizzafox** [comment]
home
codeblocks
table

**Comment by tekknolagi** [comment]
Looks good to me. Thanks for sending this along! If you want another PR, I would encourage you to see if Jekyll has a dark mode for code syntax highlighting.

**Comment by tekknolagi** [comment]
Unfortunately I had to revert in 14452f4a86b2c1adc8824251d8c7c360f279c7a8 because there was some black-on-black text. If you get a moment to fix it, great, otherwise, ah well

**Comment by pizzafox** [comment]
That's weird, which page was it?

**Comment by tekknolagi** [comment]
/blog/compiling-a-lisp-8/. I think it had to do with pre-tags in titles

**Pull request merged**
